name: Update Currency Rates

on:
  schedule:
    - cron: '*/15 * * * *'  # Every 15 minutes
  workflow_dispatch:        # Manual trigger

jobs:
  update-rates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch latest rates from FreeCurrencyAPI
        run: |
          echo "Fetching latest currency rates..."
          curl "https://api.freecurrencyapi.com/v1/latest?apikey=${{ secrets.CURRENCY_API_KEY }}&base_currency=USD" -o latest.json

          echo "Extracting rates..."
          jq '.data' latest.json > rates.json

          # Append a dummy timestamp field so the file always changes
          timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "Appending timestamp: $timestamp"
          jq --arg ts "$timestamp" '. + { "_last_updated": $ts }' rates.json > tmp.json && mv tmp.json rates.json

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        run: |
          git add rates.json
          git commit -m "Update currency rates with timestamp"
          git push
