name: Update Currency Rates

on:
  schedule:
    - cron: '0 * * * *'  # Every hour at minute 0 (e.g. 00:00, 01:00, ...)
  workflow_dispatch:       # Manual trigger

jobs:
  update-rates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch latest rates from OpenExchangeRates
        run: |
          echo "Fetching latest currency rates..."

          curl "https://openexchangerates.org/api/latest.json?app_id=${{ secrets.OPENEXCHANGE_APP_ID }}&base=USD" -o latest.json

          echo "Extracting 'rates' object..."
          jq '.rates' latest.json > rates.json

          # Append dummy timestamp to force update
          timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          jq --arg ts "$timestamp" '. + { "_last_updated": $ts }' rates.json > tmp.json && mv tmp.json rates.json

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        run: |
          git add rates.json
          git commit -m "Update currency rates with timestamp"
          git push
